apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: people-counter
  namespace: multicloud-gitops-hub
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusterDecisionResource:
    # ConfigMap with GVK information for the duck type resource
     configMapRef: my-configmap
     name: quak           # Choose either "name" of the resource or "labelSelector"
     labelSelector:
       matchLabels:       # OPTIONAL
         duck: spotted
       matchExpressions:  # OPTIONAL
       - key: duck
         operator: In
         values:
         - "spotted"
         - "canvasback"
     # OPTIONAL: Checks for changes every 60sec (default 3min)
     requeueAfterSeconds: 60
  template:
    metadata:
      name: '{{.name}}-guestbook'
    spec:
       project: "default"
       source:
         repoURL: https://github.com/argoproj/argocd-example-apps/
         targetRevision: HEAD
         path: guestbook
       destination:
         server: '{{.clusterName}}' # 'server' field of the secret
         namespace: guestbook





  project: hub
  source:
    repoURL: 'https://github.com/luisarizmendi/gitops-demo-apps'
    targetRevision: HEAD
    path: apps/people-counter/charts/people-counter-hello
    helm:
      valueFiles:
        - environments/cloud/aws1.yml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: people-counter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


